### ISSUE TITLE
FrameLayout Padding Navigation 高度

### ISSUE THREAD

**Issue by moiling** [Jude95/FitSystemWindowLayout#2]
使用情况：
腾出一个StatusBar的高度

``` xml
<FitSystemWindowsFrameLayout
            ...
            app:padding_status="true">
```

指定某子View Padding Navigation

``` xml
<ScrollView
            ...
            app:padding_navigation="true">
```

OR

``` java
Utils.paddingToNavigationBar(mScrollView);
```

结果：

![0df64966-8f22-47b7-b574-bacd25046333](https://cloud.githubusercontent.com/assets/10269126/15970490/60c62cf6-2f67-11e6-8990-f03186b8ccb9.png)

因为腾出了StatusBar，所有往下挤
有个StatusBar的高度被吃了……

**Comment by Jude95** [comment]
我的错，没注意测量子View时也要去掉statusBar。看看2.1.5有什么问题没。。

**Comment by moiling** [comment]
ScrollView不使用Utils.paddingToNavigationBar(mScrollView);都有底部Padding了……
给其他子View（直接嵌套的第一层）的app:padding_navigation="true“无效

**Comment by Jude95** [comment]
没看懂你的第一句。
普通View没有“setClipToPadding”方法。所以无效。普通View设置margin_navigation不就好了。

**Comment by moiling** [comment]
普通View是margin……我搞成padding了……我错了
第一句话的意思是我没给ScrollView设置padding它自己也有padding了，不知道是不是我误操作，我再试试
